name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and Test Android App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 (used by recent Android Gradle Plugin versions)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 4: Grant execute permission to gradlew
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # Step 5: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 7: Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 8: Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Step 9: Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
